local M = {}

local colors = {
	base00 = "#151515",
	base01 = "#1F1F1F",
	base02 = "#2E2E2E",
	base03 = "#424242",
	base04 = "#BBB6B6",
	base05 = "#E8E3E3",
	base06 = "#E8E3E3",
	base07 = "#E8E3E3",
	base08 = "#B66467",
	base09 = "#D9BC8C",
	base0A = "#D9BC8C",
	base0B = "#8C977D",
	base0C = "#8AA6A2",
	base0D = "#8DA3B9",
	base0E = "#A988B0",
	base0F = "#BBB6B6",
}

local theme = {
	Normal = { bg = colors.base00, fg = colors.base05 },
	Comment = { fg = colors.base03, italic = true },
	Constant = { fg = colors.base09 },
	String = { fg = colors.base0B },
	Character = { fg = colors.base08 },
	Number = { fg = colors.base09 },
	Boolean = { fg = colors.base09 },
	Float = { fg = colors.base09 },
	Identifier = { fg = colors.base08 },
	Function = { fg = colors.base0D },
	Statement = { fg = colors.base0D },
	Conditional = { fg = colors.base0D },
	Repeat = { fg = colors.base0D },
	Label = { fg = colors.base0D },
	Operator = { fg = colors.base05 },
	Keyword = { fg = colors.base0E },
	Exception = { fg = colors.base0D },
	PreProc = { fg = colors.base0A },
	Include = { fg = colors.base0D },
	Define = { fg = colors.base0A },
	Macro = { fg = colors.base0A },
	PreCondit = { fg = colors.base0A },
	Type = { fg = colors.base0B },
	StorageClass = { fg = colors.base0E },
	Structure = { fg = colors.base0E },
	Typedef = { fg = colors.base0B },
	Special = { fg = colors.base0C },
	SpecialChar = { fg = colors.base0C },
	Tag = { fg = colors.base0A },
	Delimiter = { fg = colors.base05 },
	SpecialComment = { fg = colors.base03 },
	Debug = { fg = colors.base08 },
	Underlined = { fg = colors.base0E, underline = true },
	Ignore = { fg = colors.base04 },
	Error = { fg = colors.base08, bold = true, underline = true },
	Todo = { fg = colors.base0A, bold = true },
	-- UI elements
	Cursor = { fg = colors.base00, bg = colors.base05 },
	CursorLine = { bg = colors.base01 },
	CursorColumn = { bg = colors.base01 },
	ColorColumn = { bg = colors.base01 },
	LineNr = { fg = colors.base03 },
	CursorLineNr = { fg = colors.base0A },
	VertSplit = { fg = colors.base02 },
	StatusLine = { fg = colors.base04, bg = colors.base01 },
	StatusLineNC = { fg = colors.base03, bg = colors.base01 },
	Folded = { fg = colors.base03, bg = colors.base01 },
	FoldColumn = { fg = colors.base03 },
	SignColumn = { fg = colors.base03 },
	Pmenu = { bg = colors.base01 },
	PmenuSel = { bg = colors.base02 },
	PmenuSbar = { bg = colors.base01 },
	PmenuThumb = { bg = colors.base03 },
	TabLine = { fg = colors.base03, bg = colors.base01 },
	TabLineSel = { fg = colors.base05, bg = colors.base02 },
	TabLineFill = { bg = colors.base01 },
	MatchParen = { bg = colors.base02 },
	Search = { bg = colors.base0A, fg = colors.base00, bold = true },
	IncSearch = { bg = colors.base09, fg = colors.base00 },
	Visual = { bg = colors.base02 },
	VisualNOS = { bg = colors.base02 },
	QuickFixLine = { bg = colors.base01, bold = true },
	Conceal = { fg = colors.base04 },
	SpellBad = { undercurl = true, sp = colors.base08 },
	SpellCap = { undercurl = true, sp = colors.base09 },
	SpellRare = { undercurl = true, sp = colors.base0A },
	SpellLocal = { undercurl = true, sp = colors.base0C },
}

function M.setup()
	for group, styles in pairs(theme) do
		vim.api.nvim_set_hl(0, group, styles)
	end
end

return M
