return {
	"IogaMaster/neocord",
	event = "VeryLazy",
	opts = {
		auto_update = true,
		blacklist = {},
		client_id = "1157438221865717891",
		debounce_timeout = 10,
		enable_line_number = true,
		logo = "https://static-00.iconduck.com/assets.00/apps-neovim-icon-2048x2048-21jvoi4h.png",
		logo_tooltip = "Hello everynyan, how are you? Fine, thank you",
		main_image = "logo",
		file_assets = {},
		global_timer = true,
		log_level = nil,
		show_time = true,
		editing_text = "Editing %s",
		file_explorer_text = "Browsing %s",
		git_commit_text = "Committing changes",
		line_number_text = "Line %s out of %s",
		plugin_manager_text = "Managing plugins",
		reading_text = "Reading %s",
		terminal_text = "Using Terminal",
		workspace_text = "I use nixos btw",
	},
}
