return {
	"IogaMaster/neocord",
	event = "VeryLazy",
	opts = {
		auto_update = true,
		blacklist = {},
		client_id = "1157438221865717891",
		debounce_timeout = 10,
		editing_text = "Editing...",
		enable_line_number = true,
		logo = "https://static-00.iconduck.com/assets.00/apps-neovim-icon-2048x2048-21jvoi4h.png",
		logo_tooltip = "Hello everynyan, how are you? Fine, thank you",
		file_assets = nil,
		file_explorer_text = "Browsing...",
		git_commit_text = "Committing changes...",
		global_timer = true,
		line_number_text = "Line %s out of %s",
		log_level = nil,
		main_image = "logo",
		plugin_manager_text = "Managing plugins...",
		reading_text = "Reading...",
		show_time = true,
		terminal_text = "Using Terminal...",
		workspace_text = "Working on %s",
	},
}
