return {
	{
		"stevearc/oil.nvim",
		enable = true,
		-- event = "VeryLazy",
		-- Optional dependencies
		dependencies = { "nvim-tree/nvim-web-devicons" },
		-- opts = {
		-- 	require("oil").setup({
		-- 		default_file_explorer = true,
		-- 		-- Id is automatically added at the beginning, and name at the end
		-- 		-- See :help oil-columns
		-- 		win_options = {
		-- 			wrap = false,
		-- 			signcolumn = "no",
		-- 			cursorcolumn = false,
		-- 			foldcolumn = "0",
		-- 			spell = false,
		-- 			list = false,
		-- 			conceallevel = 3,
		-- 			concealcursor = "nvic",
		-- 		},
		-- 		delete_to_trash = true,
		-- 		keymaps = {
		-- 			["g?"] = "actions.show_help",
		-- 			["<CR>"] = "actions.select",
		-- 			["<C-s>"] = "actions.select_vsplit",
		-- 			["<C-h>"] = "actions.select_split",
		-- 			["<C-t>"] = "actions.select_tab",
		-- 			["<C-p>"] = "actions.preview",
		-- 			["<C-c>"] = "actions.close",
		-- 			["<C-l>"] = "actions.refresh",
		-- 			["-"] = "actions.parent",
		-- 			["_"] = "actions.open_cwd",
		-- 			["`"] = "actions.cd",
		-- 			["~"] = "actions.tcd",
		-- 			["gs"] = "actions.change_sort",
		-- 			["gx"] = "actions.open_external",
		-- 			["g."] = "actions.toggle_hidden",
		-- 			["g\\"] = "actions.toggle_trash",
		-- 			["q"] = "actions.close",
		-- 		},
		-- 		-- Set to false to disable all of the above keymaps
		-- 		use_default_keymaps = true,
		-- 		view_options = {
		-- 			-- Show files and directories that start with "."
		-- 			show_hidden = true,
		-- 			-- This function defines what is considered a "hidden" file
		-- 			is_hidden_file = function(name, bufnr)
		-- 				return vim.startswith(name, ".")
		-- 			end,
		-- 			-- This function defines what will never be shown, even when `show_hidden` is set
		-- 			is_always_hidden = function(name, bufnr)
		-- 				return false
		-- 			end,
		-- 			sort = {
		-- 				-- sort order can be "asc" or "desc"
		-- 				-- see :help oil-columns to see which columns are sortable
		-- 				{ "type", "asc" },
		-- 				{ "name", "asc" },
		-- 			},
		-- 		},
		-- 		-- Configuration for the floating window in oil.open_float
		-- 		float = {
		-- 			-- Padding around the floating window
		-- 			padding = 2,
		-- 			max_width = 0,
		-- 			max_height = 0,
		-- 			border = "rounded", -- 'single' | 'double' | 'shadow' | 'curved' | ... other options supported by win open
		-- 			win_options = {
		-- 				winblend = 0,
		-- 			},
		-- 			-- This is the config that will be passed to nvim_open_win.
		-- 			-- Change values here to customize the layout
		-- 			override = function(conf)
		-- 				return conf
		-- 			end,
		-- 		},
		-- 		-- Configuration for the actions floating preview window
		-- 		preview = {
		-- 			border = "rounded", -- 'single' | 'double' | 'shadow' | 'curved' | ... other options supported by win open
		-- 			win_options = {
		-- 				winblend = 0,
		-- 			},
		-- 			-- Whether the preview window is automatically updated when the cursor is moved
		-- 			update_on_cursor_moved = true,
		-- 		},
		-- 	}),
		-- },
	},
	vim.keymap.set("n", "<leader>o", "<cmd>Oil --float<cr>", { silent = true, desc = "Open Parent Directory" }),
}
